# Generated by Django 5.2.4 on 2025-07-26 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0002_menuitem_delete_menucategories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='menu_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
