# Generated by Django 5.2.4 on 2025-07-26 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0003_alter_menuitem_menu_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='menu_name',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='named_url',
        ),
    ]
