# Generated by Django 5.2.4 on 2025-07-26 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0004_remove_menuitem_menu_name_remove_menuitem_named_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='menu_name',
            field=models.CharField(default='main_menu', max_length=50),
        ),
    ]
