# Generated by Django 5.2.4 on 2025-07-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0005_menuitem_menu_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='menu_name',
            field=models.CharField(max_length=50),
        ),
    ]
